commit test

diff --git a/.github/workflows/rasa-test.yml b/.github/workflows/rasa-test.yml
--- a/.github/workflows/rasa-test.yml
+++ b/.github/workflows/rasa-test.yml
@@ -43,11 +43,11 @@ jobs:
         run: docker run -v "$(pwd)/models:/app/models" -v "$(pwd)/results:/app/results" rauldpm/tfg-rasa:testing data-validate 2>&1 | tee -a results/output_data_validate.txt
 
       - name: Check output
-        if: grep -q "completed with errors" results/output_data_validate.txt
-        uses: actions/github-script@v3
-        with:
-          script: |
-            core.setFailed("Found errores validating nlu data")
+        run: |
+          if $(grep -q "completed with errdors" results/output_data_validate.txt); then
+            echo "Errors found in nlu data validation."
+            exit 1
+          fi
 
       - name: Run stories test
         run: docker run -v "$(pwd)/models:/app/models" -v "$(pwd)/results:/app/results" rauldpm/tfg-rasa:testing test 2>&1 | tee -a results/output_stories_tests.txt
